### ISSUE TITLE
Theme Material Design

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#1]
Build a layout to look like this:

![imagen](https://user-images.githubusercontent.com/663460/28380607-3a810932-6cb8-11e7-83c1-230e2d0a9d92.png)

Article example:

https://support.google.com/inbox/answer/6098273?hl=en&ref_topic=6067565

**Comment by Gianfranco97** [comment]
![localhost-4000-android-](https://user-images.githubusercontent.com/19965590/28542648-e63d58a4-708a-11e7-982b-d101d96c7f07.png)

![localhost-4000-android-mdm-agent-v1 2-article1](https://user-images.githubusercontent.com/19965590/28542610-c396c88a-708a-11e7-832a-515ebf04846b.png)

**Comment by Gianfranco97** [comment]
![localhost-4000-en-us-android-mdm-agent-v1 2-example 20post 20formatting](https://user-images.githubusercontent.com/19965590/28725390-44ccad2c-738b-11e7-9898-ad0acd6ca1dc.png)

![localhost-4000-en-us-android-mdm-agent-v1 2-post 20with 20a 20code 20snippet](https://user-images.githubusercontent.com/19965590/28725392-478e1f78-738b-11e7-8544-97f8d95e2834.png)

![localhost-4000-en-us-android-mdm-agent-v1 2-test 20post](https://user-images.githubusercontent.com/19965590/28725399-4b944214-738b-11e7-89b9-a7e7e488dff6.png)
