### ISSUE TITLE
Upvote for articles

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#11]
Hi, @btry 

We need an AJAX service for the Help Center, to rank the popular articles, to show in the first screen in the Help Center.

Could you create this backend service? And provide a JSON with the list of the popular repositories?

We are using Jekyll and the GitHub Pages for the deploy at the moment.

**Comment by btry** [comment]
GLPI has a knowledge base and FAQ.

Why not directly populate this and retrieve it with the API ?

**Comment by ajsb85** [comment]
@btry Good option, could you provide the documentation?
May we can create the layout on the same mobile app
