### ISSUE TITLE
Build a Jekyll site to promote the repository

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#13]
Hi, @Gianfranco97.

We need a Jekyll site in the branch gh-pages of every repository.
Use the GitHub metadata (releases, contributors...)
This is the base web page as static HTML, we need to create the Jekyll template:
https://flyve-mdm.github.io/flyve-mdm-press-kit/static-site/index.html

The bootstrap theme and guideline is here:
https://github.com/flyve-mdm/flyve-mdm-press-kit/tree/develop/bootstrap

We can discuss more features later.

Thanks

**Comment by Gianfranco97** [comment]
# Repositories included in the list
Create base commit
- [x] https://github.com/flyve-mdm/flyve-mdm-android-inventory
- [x] https://github.com/flyve-mdm/flyve-mdm-ios-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-android-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-glpi-plugin
- [x] https://github.com/flyve-mdm/flyve-mdm-glpi-demo
- [x] https://github.com/flyve-mdm/flyve-mdm-glpi-test
- [x] https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-ios-admin-dashboard
- [x] https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-docker
- [x] https://github.com/flyve-mdm/flyve-mdm-blackberry-admin-dashboard
- [x] https://github.com/flyve-mdm/flyve-mdm-blackberry-inventory
- [x] https://github.com/flyve-mdm/flyve-mdm-blackberry-inventory-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-windows-admin-dashboard
- [x] https://github.com/flyve-mdm/flyve-mdm-windows-inventory
- [x] https://github.com/flyve-mdm/flyve-mdm-windows-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-windows-inventory-agent
- [x] https://github.com/flyve-mdm/flyve-mdm-android-admin-dashboard
- [x] https://github.com/flyve-mdm/flyve-mdm-ios-inventory
- [x] https://github.com/flyve-mdm/flyve-mdm-blackberry-agent
# Repositories excluded in the list
-  ~~https://github.com/flyve-mdm/flyve-mdm-web-dashboard~~
-  ~~https://github.com/flyve-mdm/flyve-mdm.github.io~~
-  ~~https://github.com/flyve-mdm/flyve-mdm-press-kit~~
-  ~~https://github.com/flyve-mdm/glpi~~

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Could you create the project site for this repository?

https://github.com/flyve-mdm/orion-glpi-plugin

Using similar template from this one:

https://github.com/flyve-mdm/flyve-mdm-glpi-plugin

Thank you.

And btw, try updated the content of this issue.
