### ISSUE TITLE
Theme iOS

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#2]
Build a layout to look like this:

![imagen](https://user-images.githubusercontent.com/663460/28380756-c4773a94-6cb8-11e7-9f5a-036f28f84e48.png)

![imagen](https://user-images.githubusercontent.com/663460/28380767-d56a8b3a-6cb8-11e7-953f-90bd701c9b7f.png)

Article example:
https://support.apple.com/en-us/HT202033

**Comment by Gianfranco97** [comment]
![localhost-4000-ios-](https://user-images.githubusercontent.com/19965590/28543537-238639b2-708e-11e7-9504-5f2c77d1e1a5.png)


![localhost-4000-ios-mdm-agent-v1 2 1-article1](https://user-images.githubusercontent.com/19965590/28543538-240896fa-708e-11e7-9e10-72361b3157b3.png)

**Comment by Gianfranco97** [comment]
![localhost-4000-en-us-ios-mdm-agent-v1 2 1-example 20post 20formatting](https://user-images.githubusercontent.com/19965590/28725360-358af292-738b-11e7-9303-48aa20ad9fce.png)

![localhost-4000-en-us-ios-mdm-agent-v1 2 1-post 20with 20a 20code 20snippet](https://user-images.githubusercontent.com/19965590/28725366-38932b30-738b-11e7-9126-fbab5c0ba60b.png)

![localhost-4000-en-us-ios-mdm-agent-v1 2 1-test 20post](https://user-images.githubusercontent.com/19965590/28725369-3bfa541a-738b-11e7-8d36-02bc46711abe.png)
