### ISSUE TITLE
Theme Windows 10 Mobile

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#3]
Article example:
https://support.microsoft.com/en-us/help/10599/windows-10-mobile-how-to-get

![captura el 2017-07-19 a las 19 35 18](https://user-images.githubusercontent.com/663460/28380946-6c8172d6-6cb9-11e7-8ebb-fb165f9c33a9.png)

**Comment by Gianfranco97** [comment]
![localhost-4000-windows- 1](https://user-images.githubusercontent.com/19965590/28543463-da314bf8-708d-11e7-90db-c94c2b87daeb.png)


![localhost-4000-windows-mdm-agent-v1-article1 3](https://user-images.githubusercontent.com/19965590/28543464-daeab2b4-708d-11e7-8cdf-4e7218830de6.png)


![localhost-4000-windows-mdm-agent-v1-article1 4](https://user-images.githubusercontent.com/19965590/28543465-db3f085a-708d-11e7-9f89-7a9ab6763cff.png)

**Comment by Gianfranco97** [comment]
![localhost-4000-en-us-windows-mdm-agent-v1-example 20post 20formatting](https://user-images.githubusercontent.com/19965590/28725338-28f36f78-738b-11e7-8189-93e82c8578f0.png)

![localhost-4000-en-us-windows-mdm-agent-v1-post 20with 20a 20code 20snippet](https://user-images.githubusercontent.com/19965590/28725344-2c04b62c-738b-11e7-9234-5b69be39b528.png)

![localhost-4000-en-us-windows-mdm-agent-v1-test 20post](https://user-images.githubusercontent.com/19965590/28725351-2f8887ce-738b-11e7-91b9-ea58aaae24c7.png)
