### ISSUE TITLE
Theme BlackBerry 10

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#4]
Article example:

http://help.blackberry.com/en/blackberry-classic/current/help/als1342448961109.html

![captura el 2017-07-19 a las 19 36 39](https://user-images.githubusercontent.com/663460/28381065-d547ba96-6cb9-11e7-8665-31cff6d9185b.png)

**Comment by Gianfranco97** [comment]
![localhost-4000-blackberry- 1](https://user-images.githubusercontent.com/19965590/28542959-315f9864-708c-11e7-93dc-e4475fb9a6a2.png)


![localhost-4000-blackberry-inventory-agent-v1-article1 3](https://user-images.githubusercontent.com/19965590/28542965-38a4cd4c-708c-11e7-8bc7-219c48ab658d.png)


![localhost-4000-blackberry-inventory-agent-v1-article1 2](https://user-images.githubusercontent.com/19965590/28542969-395b40b8-708c-11e7-9b5e-a43d82ae5430.png)

**Comment by Gianfranco97** [comment]
![localhost-4000-en-us-blackberry-mdm-agent-v1-test 20post](https://user-images.githubusercontent.com/19965590/28725295-0974fdb0-738b-11e7-9bf5-0211d744abb5.png)

![localhost-4000-en-us-blackberry-inventory-agent-v1-example 20post 20formatting](https://user-images.githubusercontent.com/19965590/28725309-11253dfe-738b-11e7-85a8-a45747c2b507.png)

![localhost-4000-en-us-blackberry-inventory-agent-v1-post 20with 20a 20code 20snippet](https://user-images.githubusercontent.com/19965590/28725315-1520a75e-738b-11e7-9203-784951b459bd.png)
