### ISSUE TITLE
Help Center Routes

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#5]
Hi, @Gianfranco97 

We need to create several routes for the documention of all platform and versions.

Every theme is to use in the first path example /windows /blackberry /android

Example:

- [x] **https://flyve.org/blackberry/inventory-agent/v1/article-name.html**
- [x] **https://flyve.org/windows/mdm-agent/v1/article-name.html**
- [x] **https://flyve.org/android/mdm-agent/v1.2/article-name.html**
- [x] **https://flyve.org/ios/mdm-agent/v1.2.1/article-name.html**
- [x] **https://flyve.org/glpi/plugin/v1.2/article-name.html**

**Comment by ajsb85** [comment]
We forgot the route of the language.

What is the easy way for you?

- [ ] **https://flyve.org/en-US/blackberry/inventory-agent/v1/article-name.html**
- [ ] **https://flyve.org/en-US/windows/mdm-agent/v1/article-name.html**
- [ ] **https://flyve.org/en-US/android/mdm-agent/v1.2/article-name.html**
- [ ] **https://flyve.org/en-US/ios/mdm-agent/v1.2.1/article-name.html**
- [ ] **https://flyve.org/en-US/glpi/plugin/v1.2/article-name.html**

* en-GB
* es-ES
* fr-FR
* pr-BR

**Comment by Gianfranco97** [comment]
### @ajsb85 What do you mean easier?...

With or without languages?
Or the order of the route?

**Comment by ajsb85** [comment]
@Gianfranco97 The order of the route

**Comment by Gianfranco97** [comment]
The proposal that you made seems good to me.

**Comment by ajsb85** [comment]
@Gianfranco97 Nice 👍🏻

**Comment by Gianfranco97** [comment]
For reasons of technical difficulties the routes utilized will be:
- /en/ 
- /es/
- /fr/
- /pr/

NOT 

- /en-GB/
- /es-ES/
- /fr-FR/
- /pr-BR/

**Comment by Gianfranco97** [comment]
@ajsb85  en-GB and en-US they are two routes different?

**Comment by ajsb85** [comment]
@Gianfranco97 Yes

**Comment by ajsb85** [comment]
@Gianfranco97 Mandatory en-GB instead 'en'

**Comment by Gianfranco97** [comment]
Done, already exist en-US and en-GB 👍
