### ISSUE TITLE
The Robots Exclusion Protocol

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm.github.io#6]
Add the file _robots.txt_ 

```txt
User-agent: *
Disallow: /
```

The "User-agent: *" means this section applies to all robots. The "Disallow: /" tells the robot that it should not visit any pages on the site. 

![imagen](https://user-images.githubusercontent.com/663460/28409474-11ee6108-6d3b-11e7-8eac-a3172891cfe7.png)

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

This issues is urgent, could you add this file on the master branch?

Thanks.

**Comment by Gianfranco97** [comment]
Done, robots.txt file was added in master

**Comment by ajsb85** [comment]
You can close issue with the reference of the issue in the commit message.
https://help.github.com/articles/closing-issues-using-keywords/
